### ISSUE TITLE
Getting Build Failure issue after 'mvn clean install'.

### ISSUE THREAD

**Issue by kdturkar** [tada/pljava#497] opened 2024-07-28 06:15 UTC
I am using Windows 11 and Java 8. During the Cygwin setup, I added the PostgreSQL 16 package and PL/Java version 1.5.1. Despite following all the steps provided in the link below, I am still encountering a build failure issue.
Link:- https://github.com/tada/pljava/issues/1974
![Screenshot (72)](https://github.com/user-attachments/assets/b92e216f-60b8-4db7-a613-82d81b6895e4)
![Screenshot (73)](https://github.com/user-attachments/assets/8bc6649b-d671-4e8e-844d-9f325b7a0aaf)
![Screenshot (74)](https://github.com/user-attachments/assets/9a247a22-20d4-42c2-9301-5107f519242d)

@jcflack

**Comment by jcflack** [comment] 2024-07-28 14:10
> I added the PostgreSQL 16 package and PL/Java version 1.5.1. Despite following all the steps provided in the link below, I am still encountering a build failure issue.

According to PL/Java's [release notes][rnpre16], the latest PostgreSQL version the PL/Java 1.5 back branch supports is PostgreSQL 14, in PL/Java 1.5.8.

Support for PostgreSQL 13 was added in 1.5.6, and for PostgreSQL 12 was added in 1.5.3. PL/Java 1.5.1 was a release from 2018 that supported PostgreSQL up to 11.

The PL/Java 1.6 series (currently 1.6.7) is recommended for current purposes, and supports PostgreSQL 16.

Closing as an incompatible-versions issue.

[rnpre16]: https://tada.github.io/pljava/releasenotes-pre1_6.html

**Closed by jcflack** 2024-07-28 14:10 UTC

**Comment by jcflack** [comment] 2024-07-29 13:30
> Tried this as well, but still getting same build failure issue.

Details are needed to investigate any issue. If you have tried something else (some compatible combination of versions?), then please indicate the exact versions you tried, and supply the output from that try that indicates a problem.

It is more helpful to capture the build output as text and include that, than to attach screenshot images of the text.

**Comment by jcflack** [comment] 2024-07-30 16:00
This last is not the "same"—none of your reports have been the same as what preceded. The first was PL/Java 1.5.1 with PostgreSQL 16, which was simple because PG 16 is too new for PL/Java 1.5. Next was PL/Java 1.6.7 with Java 8, which was simple because Java 8 is too old for PL/Java 1.6.

This is different, because Java 11 is a supported version, and you can see the build gets further. The issue is probably related to building against a Cygwin version of PostgreSQL. Apparently the combination of Windows PL/Java 1.6 and Cygwin PostgreSQL has not been tested before (or this issue would have been reported then).

Given you have Cygwin, are you able to run this command?

```sh
pg_config | od -t x1c >out.txt
```

and then attach the text file `out.txt` to this issue?

Is there a reason you must use a Cygwin version of PostgreSQL, and not one of the Windows-native builds?
