### ISSUE TITLE
C compiler "no such file or directory" if build directory path contains a space

### ISSUE THREAD

**Issue by DavidGradwell** [tada/pljava#261] opened 2020-05-04 15:16 UTC
After downloading pljava  release 1.5.5 and going mvn clean install -e -X -Dnar.cores=1
I get:
[ERROR] clang: error: no such file or directory: '"/Users/davidjlgradwell/General Filing/P/pljava/buildMay2020/pljava-so/src/main/c/type/AclId.c"'
[ERROR] clang: error: no such file or directory: '"/Users/davidjlgradwell/General Filing/P/pljava/buildMay2020/pljava-so/src/main/c/type/Any.c"' and many similar,
[pljava build 4thMay2020.docx](https://github.com/tada/pljava/files/4575455/pljava.build.4thMay2020.docx)

Full run listing attached.

Is this a bug or my configuration problem ?

**Comment by jcflack** [comment] 2020-05-04 16:24
I'm not sure; perhaps you are discovering something we didn't know yet about Mac OS 10.15.4, or Maven 3.6.1 maybe.

Looking at the messages you copied (and the rest of them around pages 171-173 of your attachment), it seems that Maven is passing to the compiler the pathnames of C files redundantly quoted: somehow they have been wrapped in double quotes already, and then single quotes added around that, which means the compiler is probably trying to open file names with literal double-quote marks in them.

Oddly, that seems to have happened to all of the `.c` files but not to the include files.

Something you might try, hacky though it may be, would be to rename the `General Filing` directory to a name without a space in it (or make a symlink to it with a simpler name, or just move your whole PL/Java download to some other directory and build it there). I wonder whether some Maven component may be seeing the space there and saying "oh, this name contains a space, I had better put double quotes around it", and then some other Maven component is saying "oh, this name contains double quotes and a space, I had better put single quotes around it", and while this wouldn't be a solution of the problem, it might get you a successful build anyway.

I'm inclined to suspect a bug somewhere in the `nar-maven-plugin` or some one of its Maven dependencies, but curiously, I never saw it before.

**Comment by jcflack** [comment] 2020-05-04 16:26
Also, could you please include the output of the command

    pg_config

**Comment by jcflack** [comment] 2020-05-05 04:12
It's not Mac OS specific, or Maven version specific. I have just reproduced it here, as simply as renaming my build directory to have a space in the name. Again, just as in the original report, only the `.c` files get redundantly quoted.

I think somebody on the `nar-maven-plugin` team [needed more coffee][doh].

We're using a fairly old release of `nar-maven-plugin`, but that code is still there in 3.10.1.

At least you have a simple workaround.

[doh]: https://github.com/maven-nar/nar-maven-plugin/blob/7ba6ca9f3fc4385d360a8f326d20322cea1118a8/src/main/java/com/github/maven_nar/cpptasks/compiler/CommandLineCompiler.java#L439

**Comment by DavidGradwell** [comment] 2020-05-05 09:08
Thanks for the response.

First I checked that the files exist and indeed they do !

Then I moved the whole folder to a path with no space in any directory name.

Clean compiled OK.

David

**Comment by jcflack** [comment] 2020-05-07 00:15
Closing as the problem is in an upstream dependency and there is a reliable workaround.

**Closed by jcflack** 2020-05-07 00:15 UTC
