### ISSUE TITLE
pl/java PG9.3 Issue

### ISSUE THREAD

**Issue by asifnaeem** [tada/pljava#17] opened 2013-07-02 10:32 UTC
Hi,
pljava built for PG9.3 seems broken i.e.
ERROR: could not load library "/opt/pg/inst/lib/pljava.so": /opt/pg/inst/lib/pljava.so: undefined symbol: GETSTRUCT

pl/java source code require update and seems not compatible with PG 9.3. It seems that pl/java source code is moved to github but it don't build properly and gives errors start of the build i.e.
asif@uvm1:~/work/pljava$ make
make[1]: Entering directory `/home/asif/work/pljava/build/classes/pljava'
make[1]: /home/asif/work/pljava/src/java/pljava/Makefile: No such file or directory
make[1]: *** No rule to make target `/home/asif/work/pljava/src/java/pljava/Makefile'.  Stop.
make[1]: Leaving directory `/home/asif/work/pljava/build/classes/pljava'
make: *** [pljava_all] Error 2

Related build instructions seems silent on it. For the time being I pulled latest source code from cvs.pgfoundry.org and made corrections to make it work for PG 9.3. PFA patch. It seems work fine now at least for install.sql, I did not tested it further yet i.e.

asif@uvm1:~/work/postgresql/postgresql/inst$ ./bin/psql -d postgres -p 8888 -c "select version();"
                                                     version                                                     
------------------------------------------------------------------------------------------------------------------
 PostgreSQL 9.3beta2 on x86_64-unknown-linux-gnu, compiled by gcc (Ubuntu/Linaro 4.4.4-14ubuntu5.1) 4.4.5, 64-bit
(1 row)
asif@uvm1:~/work/postgresql/postgresql/inst$ ./bin/psql -d postgres -p 8888 -f /home/asif/work/pljava/src/sql/install.sql
CREATE SCHEMA
GRANT
CREATE FUNCTION
CREATE LANGUAGE
CREATE FUNCTION
CREATE LANGUAGE
CREATE TABLE
GRANT
CREATE TABLE
GRANT
ALTER TABLE
CREATE TABLE
GRANT
CREATE TABLE
GRANT
CREATE FUNCTION
CREATE FUNCTION
CREATE FUNCTION
CREATE FUNCTION
CREATE FUNCTION
CREATE FUNCTION
CREATE FUNCTION
CREATE FUNCTION
CREATE FUNCTION

Changes done are required because of move of GETSTRUCT() and timeout handling framework changes done in PG 9.3. There little more effort required ( i.e to add #if (PGSQL_MAJOR_VER >= 93) ) to make it compatible with older version of PG. Please do let me know if I missed something or more info is required. Thanks.

I am not sure how to attach patch to this ticket/issue, I am pasting the patch as following, I hope that will help i.e.

asif$ cat pljava_9.3.patch.v1
? make.install.log
? make.log
? pljava_9.3.patch.v1_beta.v1
? pljava_9.3.patch.v1_beta.v2
Index: src/C/include/pljava/pljava.h
===================================================================
RCS file: /cvsroot/pljava/org.postgresql.pljava/src/C/include/pljava/pljava.h,v
retrieving revision 1.21
diff -p -r1.21 pljava.h
*** src/C/include/pljava/pljava.h	16 Apr 2010 09:25:10 -0000	1.21
--- src/C/include/pljava/pljava.h	2 Jul 2013 08:20:57 -0000
*************** extern int vsnprintf(char* buf, size_t c
*** 34,39 ****
--- 34,46 ----
  #include <utils/memutils.h>
  #include <tcop/tcopprot.h>

+ /*
+  * GETSTRUCT require "access/htup_details.h" to be included in PG9.3
+  */
+ #if (PGSQL_MAJOR_VER > 9 || (PGSQL_MAJOR_VER == 9 && PGSQL_MINOR_VER >= 3))
+ #include "access/htup_details.h"
+ #endif
+
  /* The errorOccured will be set when a call from Java into one of the
   * backend functions results in a elog that causes a longjmp (Levels >= ERROR)
   * that was trapped using the PLJAVA_TRY/PLJAVA_CATCH macros.
Index: src/C/pljava/Backend.c
===================================================================
RCS file: /cvsroot/pljava/org.postgresql.pljava/src/C/pljava/Backend.c,v
retrieving revision 1.93
diff -p -r1.93 Backend.c
*** src/C/pljava/Backend.c	30 Mar 2012 18:00:23 -0000	1.93
--- src/C/pljava/Backend.c	2 Jul 2013 08:20:57 -0000
***************
*** 38,43 ****
--- 38,48 ----
  #include "pljava/Session.h"
  #include "pljava/SPI.h"
  #include "pljava/type/String.h"
+
+ #if (PGSQL_MAJOR_VER > 9 || (PGSQL_MAJOR_VER == 9 && PGSQL_MINOR_VER >= 3))
+ #include "utils/timeout.h"
+ #endif
+
  /* Example format: "/usr/local/pgsql/lib" */
  #ifndef PKGLIBDIR
  #error "PKGLIBDIR needs to be defined to compile this file."
*************** static void _destroyJavaVM(int status, D
*** 374,380 ****
  	{
  		Invocation ctx;
  #if !defined(WIN32)
! 		pqsigfunc saveSigAlrm;

  		Invocation_pushInvocation(&ctx, false);
  		if(sigsetjmp(recoverBuf, 1) != 0)
--- 379,385 ----
  	{
  		Invocation ctx;
  #if !defined(WIN32)
! 		TimeoutId tid;

  		Invocation_pushInvocation(&ctx, false);
  		if(sigsetjmp(recoverBuf, 1) != 0)
*************** static void _destroyJavaVM(int status, D
*** 384,396 ****
  			return;
  		}

! 		saveSigAlrm = pqsignal(SIGALRM, terminationTimeoutHandler);
! 		enable_sig_alarm(5000, false);

  		elog(DEBUG1, "Destroying JavaVM...");
  		JNI_destroyVM(s_javaVM);
! 		disable_sig_alarm(false);
! 		pqsignal(SIGALRM, saveSigAlrm);
  #else
  		Invocation_pushInvocation(&ctx, false);
  		elog(DEBUG1, "Destroying JavaVM...");
--- 389,401 ----
  			return;
  		}

! 		InitializeTimeouts();           /* establishes SIGALRM handler */
! 		tid = RegisterTimeout(USER_TIMEOUT, terminationTimeoutHandler);
! 		enable_timeout_after(tid, 5000);

  		elog(DEBUG1, "Destroying JavaVM...");
  		JNI_destroyVM(s_javaVM);
! 		disable_timeout(tid, false);
  #else
  		Invocation_pushInvocation(&ctx, false);
  		elog(DEBUG1, "Destroying JavaVM...");

**Comment by thomasgpeters** [comment] 2015-05-06 01:28
Back again:

[INFO] Preparing Nar dependencies
[INFO] Unpacking 0 dependencies to /home/thomas/Downloads/pljava-master/pljava-so/target/nar
[INFO] Compiling 51 native files
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] PostgreSQL pl/java ................................ SUCCESS [0.004s]
[INFO] PL/JAVA API ....................................... SUCCESS [0.611s]
[INFO] pl/java implementation ............................ SUCCESS [0.222s]
[INFO] pl/java deploy .................................... SUCCESS [0.019s]
[INFO] pl/java Ant Tasks ................................. SUCCESS [0.036s]
[INFO] pl/java examples .................................. SUCCESS [0.069s]
[INFO] pl/java server side library ....................... FAILURE [4.434s]
[INFO] pl/java packaging ................................. SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 7.157s
[INFO] Finished at: Tue May 05 21:24:50 EDT 2015
[INFO] Final Memory: 11M/172M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.github.maven-nar:nar-maven-plugin:3.1.0:nar-compile (default-nar-compile) on project pljava-so: NAR: Include path not found: /usr/include/postgresql/9.3/server -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal com.github.maven-nar:nar-maven-plugin:3.1.0:nar-compile (default-nar-compile) on project pljava-so: NAR: Include path not found: /usr/include/postgresql/9.3/server
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:213)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:84)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:59)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.singleThreadedBuild(LifecycleStarter.java:183)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:161)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:320)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:156)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:537)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:196)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:141)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:622)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.MojoFailureException: NAR: Include path not found: /usr/include/postgresql/9.3/server
	at com.github.maven_nar.Compiler.getCompiler(Compiler.java:632)
	at com.github.maven_nar.NarCompileMojo.createLibrary(NarCompileMojo.java:268)
	at com.github.maven_nar.NarCompileMojo.narExecute(NarCompileMojo.java:107)
	at com.github.maven_nar.AbstractNarMojo.execute(AbstractNarMojo.java:329)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:101)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:209)
	... 19 more
[ERROR] 
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :pljava-so

seems to be strange.  I have found the reference to the server director in the build.xml file in the pljava-so folder.  It is referring to a missing directory.  you can see above in the stack trace: 

Caused by: org.apache.maven.plugin.MojoFailureException: NAR: Include path not found: /usr/include/postgresql/9.3/server

I do not have a server folder anyware under postgres.  Is this supposed to be referring to another directory or to my JRE server path???

Best Regards
Thomas

**Comment by jcflack** [comment] 2015-07-20 00:22
@thomasgpeters 
> seems to be strange. I have found the reference to the server director in the build.xml file in the
> pljava-so folder. It is referring to a missing directory. you can see above in the stack trace:
>
> Caused by: org.apache.maven.plugin.MojoFailureException: NAR: Include path not found: /usr/include/postgresql/9.3/server
>
> I do not have a server folder anyware under postgres. Is this supposed to be referring to another
> directory or to my JRE server path???

I guess this should probably be on the wiki. It may depend to some extent on how different distributions choose to package PostgreSQL, but it seems common to have one package called something like `postgresql-base` that supplies the clients like `psql` and all the libraries and include files needed for building client apps to _connect to_ a PostgreSQL server, and then another package, called something like `postgresql-server`, to supply the remaining code and includes needed to build something _inside_ the server (and to supply the postgresql server itself, of course). The `/usr/include/postgresql/m.n/` directory will come from the former package, but the `server` subdirectory only from the latter.

Because PL/Java goes inside the server, it needs both packages to build against.

On another puzzle, @asifnaeem commented way back in 2013:
> [ERROR] /home/asif/work/pljava/pljava-api/src/main/java/org/postgresql/pljava/sqlgen/DDRProcessor.java:
> [102,0] illegal start of expression

which puzzled me a long time because by the Java Language Spec the code was fine, and no compiler I ever tried gave me that error, but thanks to Wander Nauta over at Stackoverflow I now know there was a range of time when Sun/Oracle's own `javac` had a bug and would give that error. There was a bug report on it, [no. 6337964](http://bugs.java.com/view_bug.do?bug_id=6337964). It was fixed in Java 7. Good to know.

**Comment by thomasgpeters** [comment] 2015-07-20 20:25
It's working now chap.

Best regards...
Thomas - 412-370-3233

**Closed** 2015-12-19 03:45 UTC
