### ISSUE TITLE
mvn clean install command not working.

### ISSUE THREAD

**Issue by kdturkar** [tada/pljava#500] opened 2024-09-16 17:36 UTC
**Versions of Java and PostgreSQL:-**
![Screenshot (166)](https://github.com/user-attachments/assets/8e71890e-3127-4db4-accd-d87725258de3)

**Folder structure of postgresql database in Cygwin:-**
![Screenshot (168)](https://github.com/user-attachments/assets/b1f62ec1-c8f5-4f5d-8858-1222201168d2)
![Screenshot (167)](https://github.com/user-attachments/assets/7f74f83b-40b1-4921-9069-b0643e8673bb)

**Getting errors after executing 'mvn clean install':-**
![Screenshot (180)](https://github.com/user-attachments/assets/c17de6a0-37d4-4d04-862c-d5a5bc4c4178)
![Screenshot (181)](https://github.com/user-attachments/assets/3cdbf49f-c74a-4c15-857a-249b1590bc68)

How I can fix this issue? Can you help in sorting out this issue @jcflack ?

**Comment by jcflack** [comment] 2024-10-04 01:20
Hello,

I notice three things in this report:

1. The PostgreSQL version is 15
2. The PL/Java version is the legacy 1.5 series (1.5.8 supports PostgreSQL up to 14)
3. The environment is Cygwin

Is there a reason your application requires the legacy 1.5 PL/Java? The 1.6 series supports more recent versions of PostgreSQL and more recent versions of Java, and has a plethora of bugs fixed.

I would recommend trying PL/Java 1.6 instead. However, the build process may fail to recognize the Cygwin environment, as there has been no effort yet to support it.

You will find, in the file `pljava-so/pom.xml`, a `var configuration = [ ... ]` array that contains the build rules for the current supported environments. If you are able, by imitating one of those entries, to add an entry whose `probe` function is true for the Cygwin environment, and whose `compile` and `link` functions do what is needed for that environment, that addition would be a good candidate to include in a future PL/Java release.

**Comment by jcflack** [comment] 2024-10-06 00:45
Closing as a duplicate of #497. The 30 July 2024 comment on #497 suggested steps for pursuing the issue further.

**Closed by jcflack** 2024-10-06 00:45 UTC
Labels: duplicate
