### ISSUE TITLE
pljava does not compile on centos 6.5 and postgres 9.4

### ISSUE THREAD

**Issue by dblanch-at-hoplasoftware** [tada/pljava#64] opened 2015-11-11 11:29 UTC
Again maybe I'm doing something wrong

I have installed using yum all packages of postgres

```
[root@localhost pljava]# yum list postgres*
Loaded plugins: fastestmirror
Loading mirror speeds from cached hostfile
 * base: mirror.uv.es
 * extras: mirror.uv.es
 * updates: mirror.uv.es
Installed Packages
postgresql94.x86_64                                                       9.4.5-1PGDG.rhel6                                           @pgdg94
postgresql94-contrib.x86_64                                               9.4.5-1PGDG.rhel6                                           @pgdg94
postgresql94-debuginfo.x86_64                                             9.4.5-1PGDG.rhel6                                           @pgdg94
postgresql94-devel.x86_64                                                 9.4.5-1PGDG.rhel6                                           @pgdg94
postgresql94-libs.x86_64                                                  9.4.5-1PGDG.rhel6                                           @pgdg94
postgresql94-plperl.x86_64                                                9.4.5-1PGDG.rhel6                                           @pgdg94
postgresql94-plpython.x86_64                                              9.4.5-1PGDG.rhel6                                           @pgdg94
postgresql94-pltcl.x86_64                                                 9.4.5-1PGDG.rhel6                                           @pgdg94
postgresql94-server.x86_64                                                9.4.5-1PGDG.rhel6                                           @pgdg94
postgresql94-test.x86_64                                                  9.4.5-1PGDG.rhel6                                           @pgdg94
```
Java mvn and gcc versions:

```
[root@localhost pljava]# java -version
java version "1.7.0_79"
Java(TM) SE Runtime Environment (build 1.7.0_79-b15)
Java HotSpot(TM) 64-Bit Server VM (build 24.79-b02, mixed mode)
[root@localhost pljava]# mvn -version
Apache Maven 3.3.3 (7994120775791599e205a5524ec3e0dfe41d4a06; 2015-04-22T11:57:37+00:00)
Maven home: /usr/local/maven
Java version: 1.7.0_79, vendor: Oracle Corporation
Java home: /usr/java/jdk1.7.0_79/jre
Default locale: es_ES, platform encoding: UTF-8
OS name: "linux", version: "2.6.32-431.el6.x86_64", arch: "amd64", family: "unix"
[root@localhost pljava]# gcc --version
gcc (GCC) 4.4.7 20120313 (Red Hat 4.4.7-16)
Copyright (C) 2010 Free Software Foundation, Inc.
Esto es software libre; vea el código para las condiciones de copia.  NO hay
garantía; ni siquiera para MERCANTIBILIDAD o IDONEIDAD PARA UN PROPÓSITO EN
PARTICULAR
```

The output of pg_config

```
[root@localhost pljava]# pg_config 
BINDIR = /usr/pgsql-9.4/bin
DOCDIR = /usr/share/doc/pgsql
HTMLDIR = /usr/share/doc/pgsql
INCLUDEDIR = /usr/pgsql-9.4/include
PKGINCLUDEDIR = /usr/pgsql-9.4/include
INCLUDEDIR-SERVER = /usr/pgsql-9.4/include/server
LIBDIR = /usr/pgsql-9.4/lib
PKGLIBDIR = /usr/pgsql-9.4/lib
LOCALEDIR = /usr/pgsql-9.4/share/locale
MANDIR = /usr/pgsql-9.4/share/man
SHAREDIR = /usr/pgsql-9.4/share
SYSCONFDIR = /etc/sysconfig/pgsql
PGXS = /usr/pgsql-9.4/lib/pgxs/src/makefiles/pgxs.mk
CONFIGURE = '--disable-rpath' '--prefix=/usr/pgsql-9.4' '--includedir=/usr/pgsql-9.4/include' '--mandir=/usr/pgsql-9.4/share/man' '--datadir=/usr/pgsql-9.4/share' '--with-perl' '--with-python' '--with-tcl' '--with-tclconfig=/usr/lib64' '--with-openssl' '--with-pam' '--with-gssapi' '--with-includes=/usr/include' '--with-libraries=/usr/lib64' '--enable-nls' '--with-uuid=e2fs' '--with-libxml' '--with-libxslt' '--with-ldap' '--with-system-tzdata=/usr/share/zoneinfo' '--sysconfdir=/etc/sysconfig/pgsql' '--docdir=/usr/share/doc' 'CFLAGS=-O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=4 -m64 -mtune=generic -I/usr/include/et' 'CPPFLAGS= -I/usr/include/et'
CC = gcc
CPPFLAGS = -I/usr/include/et -D_GNU_SOURCE -I/usr/include/libxml2 -I/usr/include
CFLAGS = -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=4 -m64 -mtune=generic -I/usr/include/et
CFLAGS_SL = -fpic
LDFLAGS = -L../../../src/common -L/usr/lib64 -Wl,--as-needed
LDFLAGS_EX = 
LDFLAGS_SL = 
LIBS = -lpgcommon -lpgport -lxslt -lxml2 -lpam -lssl -lcrypto -lgssapi_krb5 -lz -lreadline -lrt -lcrypt -ldl -lm 
VERSION = PostgreSQL 9.4.5

```

and what i get when running mvn -X -e clean install

```
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] PostgreSQL PL/Java ................................. SUCCESS [  3.301 s]
[INFO] PL/Java API ........................................ SUCCESS [  6.712 s]
[INFO] PL/Java backend Java code .......................... SUCCESS [ 11.587 s]
[INFO] PL/Java backend native code ........................ FAILURE [  6.843 s]
[INFO] PL/Java Deploy ..................................... SKIPPED
[INFO] PL/Java Ant tasks .................................. SKIPPED
[INFO] PL/Java examples ................................... SKIPPED
[INFO] PL/Java packaging .................................. SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 30.889 s
[INFO] Finished at: 2015-11-11T11:16:17+00:00
[INFO] Final Memory: 26M/69M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.github.maven-nar:nar-maven-plugin:3.1.0:nar-compile (default-nar-compile) on project pljava-so: Execution default-nar-compile of goal com.github.maven-nar:nar-maven-plugin:3.1.0:nar-compile failed. NullPointerException -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal com.github.maven-nar:nar-maven-plugin:3.1.0:nar-compile (default-nar-compile) on project pljava-so: Execution default-nar-compile of goal com.github.maven-nar:nar-maven-plugin:3.1.0:nar-compile failed.
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:224)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:862)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:286)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:197)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.PluginExecutionException: Execution default-nar-compile of goal com.github.maven-nar:nar-maven-plugin:3.1.0:nar-compile failed.
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:145)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
	... 20 more
Caused by: java.lang.NullPointerException
	at com.github.maven_nar.cpptasks.gcc.GppLinker.isClang(GppLinker.java:317)
	at com.github.maven_nar.cpptasks.gcc.GppLinker.addImpliedArgs(GppLinker.java:159)
	at com.github.maven_nar.cpptasks.compiler.CommandLineLinker.createConfiguration(CommandLineLinker.java:153)
	at com.github.maven_nar.cpptasks.compiler.AbstractLinker.createConfiguration(AbstractLinker.java:83)
	at com.github.maven_nar.cpptasks.ProcessorDef.createConfiguration(ProcessorDef.java:200)
	at com.github.maven_nar.cpptasks.CCTask.collectExplicitObjectFiles(CCTask.java:500)
	at com.github.maven_nar.cpptasks.CCTask.execute(CCTask.java:647)
	at com.github.maven_nar.NarCompileMojo.createLibrary(NarCompileMojo.java:433)
	at com.github.maven_nar.NarCompileMojo.narExecute(NarCompileMojo.java:107)
	at com.github.maven_nar.AbstractNarMojo.execute(AbstractNarMojo.java:329)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
	... 21 more
[ERROR] 
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginExecutionException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :pljava-so
[root@localhost pljava]# 
```

**Comment by jcflack** [comment] 2015-11-11 23:14
Hi,

I think you may need to install a Centos package that provides the `g++` linker. That exception comes from the [nar-maven-plugin][nmp] and there is a known [bug report][b147] about it (which also seems to name the needed Centos package: `gcc-c++`).

[nmp]: http://maven-nar.github.io/
[b147]: https://github.com/maven-nar/nar-maven-plugin/issues/147

As we have a large time zone difference, I guess you would like to know how I arrived at that information. :) I began by reading down the chain of `Caused by:` exceptions in your stack trace to find the original one:

```
Caused by: java.lang.NullPointerException
    at com.github.maven_nar.cpptasks.gcc.GppLinker.isClang(GppLinker.java:317)
```
But line 317 could be different in another version of `nar-maven-plugin`, so the exact plugin version is important, from the first line of the message:
```
[ERROR] Failed to execute goal com.github.maven-nar:nar-maven-plugin:3.1.0:nar-compile (default-nar-compile) on project pljava-so: Execution default-nar-compile of goal com.github.maven-nar:nar-maven-plugin:3.1.0:nar-compile failed. NullPointerException -> [Help 1]
```
So it's version 3.1.0. That's enough information to go to the `nar-maven-plugin` [homepage][nmp] and use its "Project Information" link to find its source repository, which is conveniently [on GitHub][nmps], and then go to the [releases tab][rels].

[nmps]: https://github.com/maven-nar/nar-maven-plugin
[rels]: https://github.com/maven-nar/nar-maven-plugin/releases

Choosing the commit id ([2124f0e][sha310]) for release 3.1.0, then "browse files", then finding the class `com.github.maven_nar.cpptasks.gcc.GppLinker` leads straight to the offending [line 317][l317]. Sure enough, it looks like `cmdout` might be null in some case if the linker `cmd` failed (for example, if it is not installed).

[sha310]: https://github.com/maven-nar/nar-maven-plugin/commit/2124f0e0045cf37c18e5f03a3066aacdf2e601df
[l317]: https://github.com/maven-nar/nar-maven-plugin/blob/2124f0e0045cf37c18e5f03a3066aacdf2e601df/src/main/java/com/github/maven_nar/cpptasks/gcc/GppLinker.java#L317

Then I looked for the [same line in the HEAD version][head333]. Aha! Someone has added a null check. :) Click `Blame` and it shows [when that line was changed][chkadd]. And the message in that commit identifies the bug report ([fixes 147][b147]), so there's the explanation.

[head333]: https://github.com/maven-nar/nar-maven-plugin/blob/master/src/main/java/com/github/maven_nar/cpptasks/gcc/GppLinker.java#L333
[chkadd]: https://github.com/maven-nar/nar-maven-plugin/commit/d97d1826808bf007bc44c1c432a77594d5261a44

It would also be nice to know which version of `nar-maven-plugin` has that fixed, so PL/Java's build can be updated to use that version. In the same commit where that change was made, the `pom.xml` file says `<version>3.2.4-SNAPSHOT</version>`, so the problem should be fixed in that plugin starting with release 3.2.4.  Sadly, as the [releases page][rels] showed, there hasn't been a release 3.2.4 yet, so I will have to wait before updating PL/Java to use it.

But meanwhile, if you install `g++`, you should stop having that problem. :)

-Chap

**Comment by jcflack** [comment] 2015-11-12 18:35
Hi,

Did that help? Any progress?

-Chap

**Comment by dblanch-at-hoplasoftware** [comment] 2015-11-13 04:33
Yep! it compiles! now I’m about to configure postgres with pl/java.

I’m documenting all the steps I needed to take to make it work. i’ll write them when i finish with success.

Thanks.

**Comment by dblanch-at-hoplasoftware** [comment] 2015-11-13 06:27
It seems it's working ... not without a rough fight with pljava.so and LD_LIBRARY_PATH, but at the end it works. :)

I'll try to document all and write it down so others can benefit of my work.

```
test=# \i /vagrant/pljava/src/sql/install.sql 
CREATE SCHEMA
GRANT
CREATE FUNCTION
CREATE LANGUAGE
CREATE FUNCTION
CREATE LANGUAGE
CREATE TABLE
GRANT
CREATE TABLE
GRANT
CREATE TABLE
GRANT
CREATE TABLE
GRANT
CREATE TABLE
GRANT
CREATE FUNCTION
CREATE FUNCTION
CREATE FUNCTION
CREATE FUNCTION
CREATE FUNCTION
CREATE FUNCTION
CREATE FUNCTION
CREATE FUNCTION
CREATE FUNCTION

test=# CREATE OR REPLACE FUNCTION getsysprop(VARCHAR)
  RETURNS VARCHAR
  AS 'java.lang.System.getProperty'
  LANGUAGE java;
CREATE FUNCTION
test=# SELECT getsysprop('user.home');
   getsysprop   
----------------
 /var/lib/pgsql
(1 row)
```

**Comment by jcflack** [comment] 2015-11-13 06:38
Great!  Did you receive the e-mail I tried to send you at Hopla?  (I used the web contact form, maybe it didn't go anywhere.) It would be great if you could try the branch I mentioned there, and compare that setup experience to what you just had with this ... but we could do that on e-mail instead of this ticket.

**Comment by dblanch-at-hoplasoftware** [comment] 2015-11-17 07:55
To make it work you have to install these things:

```
	# install postgres 9.4 + devel packages devel

	# install java 1.7 I wasn't able to make it work with any other java :(
	# file jdk-7u79-linux-x64.rpm must be downloaded first
	sudo yum install /vagrant/jdk-7u79-linux-x64.rpm -y

	# install maven from latest release available 
	# install git
	
	# install Development Tools
	sudo yum groupinstall 'Development Tools' -y
	
	# download and compile pl/javat
	git clone https://github.com/tada/pljava.git
	# compile pl/java
	export PATH=/usr/pgsql-9.4/bin/:$PATH
	cd pljava
	/usr/local/maven/bin/mvn clean install
	
	# install pl/java in postgres
	# copy library to postgres lib directory
	sudo cp pljava/pljava-so/target/nar/pljava-so-0.0.2-SNAPSHOT-amd64-Linux-gpp-shared/lib/amd64-Linux-gpp/shared/libpljava-so-0.0.2-SNAPSHOT.so /usr/pgsql-9.4/lib/
	# create pljava.so and link to library
	sudo ln -s /usr/pgsql-9.4/lib/libpljava-so-0.0.2-SNAPSHOT.so /usr/pgsql-9.4/lib/pljava.so
	# copy jar in postgres lib directory (may be this need a revision)
	sudo cp pljava/pljava/target/pljava-0.0.2-SNAPSHOT.jar /usr/pgsql-9.4/lib/
	# configure posgres.conf
	sudo echo "pljava.classpath='/usr/pgsql-9.4/lib/pljava-0.0.2-SNAPSHOT.jar'" >> /var/lib/pgsql/9.4/data/postgresql.conf
	# configure LD_LIBRARY_PATH to use java
	sudo echo 'LD_LIBRARY_PATH=/usr/java/jdk1.7.0_79/jre/lib/amd64/server' >> /var/lib/pgsql/.bash_profile 
	sudo echo 'export LD_LIBRARY_PATH' >> /var/lib/pgsql/.bash_profile
	# finally restart server to get enviroment variables and new configuration

	# After this you can log as postgres, create a database 'test', connect to that database and execute the script
	# pljava/src/sql/install.sql

```
I hope it helps.

**Closed** 2015-12-19 03:48 UTC
